MODEL_NAME="all-MiniLM-L6-v2"
MODEL_NAME_CLIP="clip-ViT-B-32"
PINECONE_API_KEY=""
PINECONE_INDEX_NAME=""
PINECONE_REGION=""
OPEN_AI_API_KEY=""
aws_access_key_id = ''
aws_secret_access_key = ''
IMAGES_PATH =""
